version: '3'
services:
  gretl:
    image: sogis/gretl:${GRETL_IMAGE_TAG:-2.2.373}
    entrypoint: ["gretl", "--project-cache-dir=/home/gradle/projectcache"]
    volumes:
      - type: bind
        source: $HOME/gretljobs.properties
        target: /home/gradle/.gradle/gradle.properties
      - type: bind
        source: .
        target: /home/gradle/project
      - type: bind
        source: ${TMP:-/tmp}
        target: /gretl-share
    depends_on:
      - oereb-db
      - edit-db
  edit-db:
    image: sogis/oereb-db:2
    environment:
      POSTGRES_DB: edit
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST_AUTH_METHOD: md5
      PG_WRITE_PWD: ddluser
      PG_READ_PWD: dmluser
      PG_GRETL_PWD: gretl

    ports:
      - "54321:5432"
  oereb-db:
    image: sogis/oereb-db:2
    environment:
      POSTGRES_DB: oereb
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST_AUTH_METHOD: md5
      PG_WRITE_PWD: ddluser
      PG_READ_PWD: dmluser
      PG_GRETL_PWD: gretl
    ports:
      - "54323:5432"