version: '3'
services:
  gretl:
    image: sogis/gretl-runtime
    entrypoint: /bin/sh
    command: -c "cd /home/gradle/; gretl"
    environment:
      ORG_GRADLE_PROJECT_dbUriEdit: $ORG_GRADLE_PROJECT_dbUriEdit
      ORG_GRADLE_PROJECT_dbUserEdit: $ORG_GRADLE_PROJECT_dbUserEdit
      ORG_GRADLE_PROJECT_dbPwdEdit: $ORG_GRADLE_PROJECT_dbPwdEdit
      ORG_GRADLE_PROJECT_dbUriOereb: "jdbc:postgresql://db/oereb"
      ORG_GRADLE_PROJECT_dbUserOereb: gretl
      ORG_GRADLE_PROJECT_dbPwdOereb: gretl
    depends_on:
      - oereb_db
      - edit_db
  oereb_db:
    image: sogis/oereb-db
    environment:
      PG_DATABASE: oereb
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    hostname: oereb_db
    ports:
      - "54321:5432"
    volumes:
      - /tmp:/pgdata
  edit_db:
    image: sogis/oereb-db
    command: /tmp/override_setupsql.sh /opt/cpm/bin/start.sh
    environment:
      PG_DATABASE: edit
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    hostname: edit_db
    ports:
      - "54322:5432"
    volumes:
      - /tmp:/pgdata
      - ${PWD}/override_setupsql.sh:/tmp/override_setupsql.sh
